version: 2.1

orbs:
  aws-cli: circleci/aws-cli@5.3.1
  ansible-playbook: orbss/ansible-playbook@0.0.5

jobs:
  execute-cloudformation:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          aws_access_key_id: AWS_ACCESS_KEY_ID
          aws_secret_access_key: AWS_SECRET_ACCESS_KEY
          region: AWS_DEFAULT_REGION
      - run:
          name: debug file structure
          command: |
            ls -la
      - run:
          name: Deploy Cloudformation
          command: |
            set -x
            aws cloudformation deploy --stack-name "my-new-stack" --template-file "cloudformation/sampleStack.yml"
  execute-ansible:
      executor: ansible-playbook/default
      working_directory: ~/project
      steps:
        - checkout
        - add_ssh_keys:
            fingerprisnts:
              - "SHA256:C/2Tyc2h823YnNy9EMJfkoLmRI4b7hFIQKlf7mC2whU"
        - ansible-playbook/install:
            version: 2.10.7
#         - ansible-playbook/playbook:
#             playbook: playbook.yml
#             playbook-options: --list-hosts -i inventory
        - ansible-playbook/playbook:
            playbook: playbook.yml
            playbook-options: -u ec2-user -i inventory --private-key ~/.ssh/id_rsa --ssh-extra-args="-o ControlMaster=auto -o ControlPersist=60 -o StrictHostKeyChecking=no"

workflows:
  application-provisioning:
    jobs:
      - execute-cloudformation
      - execute-ansible:
          requires:
            - execute-cloudformation
